<a href="https://colab.research.google.com/github/RageshRathod/Machine-Learning/blob/main/Energy_Generation_Prediction_on_Machine_Learning__faulty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing The Dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[ : , :-1].values
y = dataset.iloc[ : , -1].values

In [ ]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


# Checking Missing Values

In [ ]:
dataset.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


# Splitting the Data in Training and Testing

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=10)

In [ ]:
x_train.shape

(7654, 4)

In [ ]:
x_test.shape

(1914, 4)

# Training on Multiple Linear Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

# Predicting the test Value for Multiple Linear Regression Model

In [ ]:
y_pred1 = mlr.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1),y_test.reshape(len(y_test),1)),1))

[[456.62 456.57]
 [445.02 438.7 ]
 [438.87 436.09]
 ...
 [433.82 431.27]
 [443.17 441.17]
 [461.8  461.08]]


# Training  on Polynomial Regression Model

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
x_poly = poly_reg.fit_transform(x_train)
plr = LinearRegression()
plr.fit(x_poly,y_train)

LinearRegression()

# Predicting test value on  Polynomial Regression Model

In [ ]:
y_pred2 = plr.predict(poly_reg.fit_transform(x_test))
np.set_numeric_ops(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test.reshape(len(y_test),1)),1))

[[456.01 456.57]
 [442.62 438.7 ]
 [442.88 436.09]
 ...
 [432.9  431.27]
 [441.44 441.17]
 [459.44 461.08]]


<ipython-input-13-8d45e5727473>:2: DeprecationWarning: PyArray_SetNumericOps is deprecated. Use PyUFunc_ReplaceLoopBySignature to replace ufunc inner loop functions instead.
  np.set_numeric_ops(precision=2)


# Training Model on Support Vector Method (SVR)

## Feature Scaling Of X and Y Values

In [ ]:
y1 = y.reshape(len(y),1)

## Splitting the Dataset

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y1_train,y1_test = train_test_split(x,y1, test_size=0.2, random_state=10)

In [ ]:
y1_test.shape

(1914, 1)

In [ ]:
x_train.shape

(7654, 4)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_y.fit_transform(x_test)

# Training the Model on SVR Model

In [ ]:
from sklearn.svm import SVR
svlr = SVR(kernel='rbf')
svlr.fit(x_train,y1_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the Values on Suport Vector Model

In [ ]:
y_pred3 = sc_y.inverse_transform(svlr.predict([[sc_x.fit_transform(x_test)]]))

NameError: ignored

# Testing Model on Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state = 2)
dtr.fit(x_train,y_train)

Predicting the Test Value on Decision Tree Regression

In [ ]:
y_pred4 = dtr.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred4.reshape(len(y_pred4),1),y_test.reshape(len(y_test),1)),1))

# Training Model on Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfrr = RandomForestRegressor(n_estimators=5, random_state =0)
rfrr.fit(x_train,y_train)

# Predicting the Value On the Basis of Random Forest Model

In [ ]:
y_pred5 = rfrr.predict(x_test)
np.set_printoptions(precision =2)
print(np.concatenate((y_pred5.reshape(len(y_pred5),1),y_test.reshape(len(y_test),1)),1))

## Evaluating the Performance of Multiple Linear Regression Model

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_pred1,y_test)

# Evaluating the Performance of Polynomial Regression

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_pred2,y_test)

# Evaluating the Performance of Support Vector Function

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_pred3,y_test)

# Evaluating the Performance of Decision Tree Regression

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_pred4,y_test)

## Evaluating the Performance of Random Forest Regression

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_pred5,y_test)